### ISSUE TITLE
captcha

### ISSUE THREAD

**Issue by kmatrosova** [ever3001/selenium_rdv_visa#1]
Hello, I've been trying to use your script but I get this message: 

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="nationalite"]"}.

I guess when you coded your script it was all on the same page, however now you first have to fill in a captcha, and only after that you can fill the field "nationalite". Your script gets stuck on the captcha field. Any ideas of how to fix this?

**Comment by ever3001** [comment]
Hey hello @kmatrosova,

This code is more than 2 years old, and I haven't had the time to update the code or to see if the process is still the same. After what you tell me, I believe they added a captcha to stop bots like this one from trying all day (from my experience, I know it is necessary to get an appointment in Paris). Therefore, there should be a Python module to automatically resolve captchas, but I'm not sure if something like that exists.

If you find something that works, do not hesitate to make a merge request for implementing the feature.

Have a nice day and bon courage !
