### ISSUE TITLE
rendez vous

### ISSUE THREAD

**Issue by Mira1234911** [ever3001/selenium_rdv_visa#3]
https://github.com/ever3001/rendez_bot/blame/b13212018dd7099eaed3ddbb343c1bf776ee87e8/README.md#L159

**Comment by ever3001** [comment]
Hi,

Thank you for reaching out. Unfortunately, I am not actively maintaining this project at the moment and won't be able to implement new features or address issues until further notice.

If you need the implementation for "Seine-Saint-Denis (93)", I encourage you to contribute by writing the necessary logic and submitting a pull request. I’ll do my best to review it and merge it into the project if it meets the requirements.

Thank you for your understanding
